[PortableApps.comTheme]
PortableApps.comThemeVersion=2.0
PortableApps.comThemeType=Simple

[ThemeDetails]
Name=Lazarus PE
Version=2.0
Author=Commander Rescue
URL=http://portableapps.com/

[ButtonApplications]
FontColor=FFFFFF
IconTransparentColor=000000
DividerColor=106E7E

[ButtonFolders]
FontColor=FFFFFF
FontColorWhite=FFFFFF

[DriveSpace]
FontColor=E6EDF3
FontShadowColor=000000
StretchImage=true

[SearchBox]
FontColor=E6F7FA
BackgroundColor=03181B
BorderColor=1EC8E6

[Menu]
Layout=modern
Chrome=custom
Matte=none
Background=none
DefaultBackgroundColor=Silver
PinkBackgroundColor=ef81cb
RedBackgroundColor=7d0003
OrangeBackgroundColor=fb9f32
YellowBackgroundColor=f4ee45
GreenBackgroundColor=9acd3d
BlueBackgroundColor=63b4fb
;BackgroundColor=0D276E ;BLUE2
PurpleBackgroundColor=7113bb
VioletBackgroundColor=c37cfb
BlackBackgroundColor=343434
WhiteBackgroundColor=fbfbfb
GrayBackgroundColor=535353
SilverBackgroundColor=979797
BronzeBackgroundColor=a97452
GoldBackgroundColor=edc518